import { avatarUrl } from "@/lib/utils";
import type { SkillLevel } from "@/types/player";
import type { LeaderboardPlayer } from "./types";

export const RANKING_CITIES = [
  "All",
  "Bangalore",
  "Mumbai",
  "Delhi",
  "Chennai",
  "Hyderabad",
  "Pune",
  "Kolkata",
] as const;

export const LEADERBOARD_PLAYERS: LeaderboardPlayer[] = [
  {
    id: "p1",
    rank: 1,
    fullName: "Priya Sharma",
    avatarUrl: avatarUrl("priya-sharma"),
    city: "Bangalore",
    skillLevel: "4.5",
    duprRating: 4.65,
    singlesRating: 4.68,
    doublesRating: 4.61,
    wins: 58,
    losses: 12,
    winPct: 83,
    currentStreak: 8,
  },
  {
    id: "p2",
    rank: 2,
    fullName: "Rohan Desai",
    avatarUrl: avatarUrl("rohan-desai"),
    city: "Bangalore",
    skillLevel: "4.5",
    duprRating: 4.52,
    singlesRating: 4.49,
    doublesRating: 4.55,
    wins: 51,
    losses: 18,
    winPct: 74,
    currentStreak: 3,
  },
  {
    id: "p3",
    rank: 3,
    fullName: "Ananya Iyer",
    avatarUrl: avatarUrl("ananya-iyer"),
    city: "Bangalore",
    skillLevel: "4.0",
    duprRating: 4.41,
    singlesRating: 4.44,
    doublesRating: 4.38,
    wins: 44,
    losses: 16,
    winPct: 73,
    currentStreak: 5,
  },
  {
    id: "p4",
    rank: 4,
    fullName: "Arjun Mehta",
    avatarUrl: avatarUrl("arjun-mehta"),
    city: "Bangalore",
    skillLevel: "4.0",
    duprRating: 4.12,
    singlesRating: 4.15,
    doublesRating: 4.08,
    wins: 32,
    losses: 15,
    winPct: 68,
    currentStreak: 5,
    isCurrentUser: true,
  },
  {
    id: "p5",
    rank: 5,
    fullName: "Vikram Patel",
    avatarUrl: avatarUrl("vikram-patel"),
    city: "Mumbai",
    skillLevel: "4.0",
    duprRating: 4.05,
    singlesRating: 4.02,
    doublesRating: 4.08,
    wins: 38,
    losses: 20,
    winPct: 66,
    currentStreak: 1,
  },
  {
    id: "p6",
    rank: 6,
    fullName: "Sneha Reddy",
    avatarUrl: avatarUrl("sneha-reddy"),
    city: "Hyderabad",
    skillLevel: "3.5",
    duprRating: 3.98,
    singlesRating: 3.95,
    doublesRating: 4.01,
    wins: 29,
    losses: 17,
    winPct: 63,
    currentStreak: 2,
  },
  {
    id: "p7",
    rank: 7,
    fullName: "Karan Singh",
    avatarUrl: avatarUrl("karan-singh"),
    city: "Delhi",
    skillLevel: "4.0",
    duprRating: 4.22,
    singlesRating: 4.25,
    doublesRating: 4.18,
    wins: 41,
    losses: 22,
    winPct: 65,
    currentStreak: 4,
  },
  {
    id: "p8",
    rank: 8,
    fullName: "Meera Nair",
    avatarUrl: avatarUrl("meera-nair"),
    city: "Chennai",
    skillLevel: "3.5",
    duprRating: 3.85,
    singlesRating: 3.88,
    doublesRating: 3.82,
    wins: 26,
    losses: 14,
    winPct: 65,
    currentStreak: 6,
  },
  {
    id: "p9",
    rank: 9,
    fullName: "Aditya Joshi",
    avatarUrl: avatarUrl("aditya-joshi"),
    city: "Pune",
    skillLevel: "3.5",
    duprRating: 3.72,
    singlesRating: 3.7,
    doublesRating: 3.74,
    wins: 22,
    losses: 18,
    winPct: 55,
    currentStreak: 0,
  },
  {
    id: "p10",
    rank: 10,
    fullName: "Divya Krishnan",
    avatarUrl: avatarUrl("divya-krishnan"),
    city: "Chennai",
    skillLevel: "3.0",
    duprRating: 3.55,
    singlesRating: 3.58,
    doublesRating: 3.52,
    wins: 18,
    losses: 12,
    winPct: 60,
    currentStreak: 3,
  },
  {
    id: "p11",
    rank: 11,
    fullName: "Rahul Verma",
    avatarUrl: avatarUrl("rahul-verma"),
    city: "Kolkata",
    skillLevel: "3.0",
    duprRating: 3.42,
    singlesRating: 3.4,
    doublesRating: 3.44,
    wins: 15,
    losses: 16,
    winPct: 48,
    currentStreak: 1,
  },
  {
    id: "p12",
    rank: 12,
    fullName: "Isha Gupta",
    avatarUrl: avatarUrl("isha-gupta"),
    city: "Mumbai",
    skillLevel: "3.0",
    duprRating: 3.3,
    singlesRating: 3.32,
    doublesRating: 3.28,
    wins: 12,
    losses: 14,
    winPct: 46,
    currentStreak: 2,
  },
].map((player) => ({
  ...player,
  strengthRating:
    Math.round(player.duprRating * (player.winPct / 100) * 100) / 100,
})) as LeaderboardPlayer[];

export const SKILL_FILTER_OPTIONS: Array<SkillLevel | "All"> = [
  "All",
  "2.0",
  "2.5",
  "3.0",
  "3.5",
  "4.0",
  "4.5",
  "5.0+",
];
